name: Test Self Hosted Runners
on:
  - pull_request
  - workflow_dispatch
jobs:
  job1_cpu:
    runs-on: linux-amd64-cpu8
    steps:
      - name: hello
        run: echo "hello"
  job2_gpu:
    runs-on: linux-amd64-gpu-v100-latest-1
    container:
      image: nvidia/cuda:12.0.0-base-ubuntu22.04
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update and install things
        run: |
          apt-get -qq update
          apt-get install --yes curl bzip2 git
      - name: Setup conda env
        run: |
          cd ..
          mkdir bin
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          eval "$(bin/micromamba shell hook -s posix)"
          micromamba create -y -n sklearn-gpu -c conda-forge python=3.10 numpy scipy cython joblib threadpoolctl compilers scipy
          cd -
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install _custom_ scikit-learn version
        run: |
          mkdir ../scikit-learn
          cd ../scikit-learn
          git clone https://github.com/scikit-learn/scikit-learn
          cd scikit-learn
          git checkout feature/engine-api
          ../../bin/micromamba run -n sklearn-gpu python -m pip install --no-build-isolation -e .
          cd ../../scikit-learn-nv
      - name: Install plugin
        run: |
          ../bin/micromamba run -n sklearn-gpu python -c "import sklearn; print('scikit-learn version:', sklearn.__version__)"
          
