name: Test Self Hosted Runners
on:
  - pull_request
  - workflow_dispatch
jobs:
  job1_cpu:
    runs-on: linux-amd64-cpu8
    steps:
      - name: hello
        run: echo "hello"
  job2_gpu:
    runs-on: linux-amd64-gpu-v100-latest-1
    container:
      image: nvidia/cuda:12.0.0-base-ubuntu22.04
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update and install things
        run: |
          apt-get -qq update
          apt-get install --yes curl
      - name: hello
        run: |
          echo "directory"
          pwd
          ls
          mkdir bin
          echo installing umamba
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ls
          ./bin/micromamba
          eval "$(./bin/micromamba shell hook -s posix)"
          micromamba
          
