name: Test Self Hosted Runners
on:
  - pull_request
  - workflow_dispatch
jobs:
  job1_cpu:
    runs-on: linux-amd64-cpu8
    steps:
      - name: hello
        run: echo "hello"
  job2_gpu:
    runs-on: linux-amd64-gpu-v100-latest-1
    container:
      image: nvidia/cuda:12.0.0-base-ubuntu22.04
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update and install things
        run: |
          apt-get -qq update
          apt-get install --yes curl bzip2
      - name: Setup conda env
        run: |
          cd ..
          mkdir bin
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          eval "$(bin/micromamba shell hook -s posix)"
          micromamba create -y -n sklearn-gpu -c conda-forge python=3.10 numpy scipy cython joblib threadpoolctl compilers scipy
          cd -
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: List repository contents
        run: |
          ../bin/micromamba run -n sklearn-gpu python -v
          echo "repo contents"
          ls
          
