name: Test Self Hosted Runners
on:
  - pull_request
  - workflow_dispatch
jobs:
  job1_cpu:
    runs-on: linux-amd64-cpu8
    steps:
      - name: hello
        run: echo "hello"
  job2_gpu:
    runs-on: linux-arm64-gpu-a100-latest-1
    container:
      image: nvidia/cuda:12.0.0-base-ubuntu22.04
      env:
        NVIDIA_VISIBLE_DEVICES: "0"
    steps:
      - name: hello
        run: |
          echo "hello"
          nvidia-smi
